### ISSUE TITLE
Trying to save to C:\Users\Ritesh Raj\Documents\temp.txt

### ISSUE THREAD

**Issue by EricVdB** [ritesh28393/ChartJS.Helpers.MVC#1]
I tried your ChartJs Helper, but when trying to show the graph, it throws an error:

Could not find a part of the path 'C:\Users\Ritesh Raj\Documents\temp.txt'.

Looking at the source code i found below line in ToJson.cs:
`private static FileStream stream = new FileStream(@"C:\Users\Ritesh Raj\Documents\temp.txt",FileMode.Append);
`

Is that a leftover of a test?

Can you give this a look?

Thanks in advance,
Eric

**Comment by ritesh28393** [comment]
Hi Eric,

Thanks for bringing it up.

The mentioned code was for testing purpose. I have removed it. 

Regards,,
Ritesh
