### ISSUE TITLE
Multiple Y-Axis

### ISSUE THREAD

**Issue by cantareamantisest** [ritesh28393/ChartJS.Helpers.MVC#3]
How to set two scale Y-axis, using ChartJS.Helper.MVC?

**Comment by ritesh28393** [comment]
goto **MultiAxis()** in https://github.com/ritesh28393/ChartJS.Helpers.MVC/blob/master/SampleMVC/Controllers/LineChartsController.cs

you can find more examples at https://github.com/ritesh28393/ChartJS.Helpers.MVC/tree/master/SampleMVC

**Comment by cantareamantisest** [comment]
Thanks for help. Excellent wrapper.
